/* ============================================================================
   HOSPITAL MANAGEMENT — MY SNOWFLAKE QUERIES
   ----------------------------------------------------------------------------
   All queries written and run in Snowflake, consolidated into one file.
   ============================================================================ */

USE DATABASE HOSPITAL_MANAGEMENT;
USE SCHEMA PUBLIC;


-- ============================================================
-- Table checks (view all data in each table)
-- ============================================================
SELECT * FROM DIM_PATIENT;
SELECT * FROM DIM_DEPARTMENT;
SELECT * FROM DIM_DOCTOR;
SELECT * FROM DIM_DATE;
SELECT * FROM FACT_APPOINTMENT;


-- Q1. Patients from Tamil Nadu
SELECT * FROM DIM_PATIENT WHERE STATE = 'Tamil Nadu';

-- Q2. All Completed appointments
SELECT * FROM FACT_APPOINTMENT WHERE STATUS = 'Completed';

-- Q3. Appointments with billing amount above ₹10,000
SELECT * FROM FACT_APPOINTMENT WHERE BILLING_AMOUNT > 10000;

-- Q4. Male vs Female patient count
SELECT GENDER, COUNT(*)
FROM DIM_PATIENT
GROUP BY GENDER;

-- Q5. Doctors and department, sorted by experience
SELECT DOCTOR_NAME, DEPARTMENT_ID, EXPERIENCE_YEARS
FROM DIM_DOCTOR
ORDER BY EXPERIENCE_YEARS DESC;

-- Q6. Total revenue by department
SELECT D.DEPARTMENT_NAME, SUM(F.BILLING_AMOUNT)
FROM DIM_DEPARTMENT D
INNER JOIN FACT_APPOINTMENT F ON D.DEPARTMENT_ID = F.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;

-- Q7. Appointments handled by each doctor (doctor workload)
SELECT D.DOCTOR_NAME, COUNT(F.APPOINTMENT_ID)
FROM DIM_DOCTOR D
JOIN FACT_APPOINTMENT F ON D.DOCTOR_ID = F.DOCTOR_ID
GROUP BY D.DOCTOR_NAME
ORDER BY COUNT(F.APPOINTMENT_ID) DESC;

-- Q8. Average treatment cost by appointment type
SELECT APPOINTMENT_TYPE, AVG(TREATMENT_COST)
FROM FACT_APPOINTMENT
WHERE STATUS = 'Completed'
GROUP BY APPOINTMENT_TYPE
ORDER BY AVG(TREATMENT_COST) DESC;

-- Q9. Patient visit frequency
SELECT P.PATIENT_ID, P.PATIENT_NAME, COUNT(F.PATIENT_ID)
FROM DIM_PATIENT P
JOIN FACT_APPOINTMENT F ON P.PATIENT_ID = F.PATIENT_ID
GROUP BY P.PATIENT_ID, P.PATIENT_NAME
ORDER BY COUNT(F.PATIENT_ID) DESC;

-- Q10. Monthly appointment volume and revenue
SELECT D.MONTH_NAME, D.MONTH, COUNT(F.APPOINTMENT_ID), SUM(F.BILLING_AMOUNT)
FROM DIM_DATE D
JOIN FACT_APPOINTMENT F ON D.DATE_ID = F.DATE_ID
GROUP BY D.MONTH_NAME, D.MONTH
ORDER BY D.MONTH;

-- Q11. Full appointment detail (patient, doctor, department, date, cost)
SELECT P.PATIENT_NAME, D.DOCTOR_NAME, DE.DEPARTMENT_NAME, DAT.FULL_DATE,
       F.APPOINTMENT_TYPE, F.STATUS, F.BILLING_AMOUNT
FROM FACT_APPOINTMENT F
JOIN DIM_PATIENT P     ON P.PATIENT_ID = F.PATIENT_ID
JOIN DIM_DOCTOR D      ON D.DOCTOR_ID = F.DOCTOR_ID
JOIN DIM_DEPARTMENT DE ON DE.DEPARTMENT_ID = F.DEPARTMENT_ID
JOIN DIM_DATE DAT      ON DAT.DATE_ID = F.DATE_ID;

-- Q13. Departments generating more than ₹50,00,000 in revenue
SELECT D.DEPARTMENT_NAME, SUM(F.BILLING_AMOUNT)
FROM DIM_DEPARTMENT D
JOIN FACT_APPOINTMENT F ON D.DEPARTMENT_ID = F.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING SUM(F.BILLING_AMOUNT) > 5000000;

-- Q14. Doctors whose average treatment cost is above the hospital-wide average
SELECT D.DOCTOR_NAME, AVG(F.TREATMENT_COST)
FROM DIM_DOCTOR D
JOIN FACT_APPOINTMENT F ON D.DOCTOR_ID = F.DOCTOR_ID
WHERE F.STATUS = 'Completed'
GROUP BY D.DOCTOR_NAME
HAVING AVG(F.TREATMENT_COST) >
    (SELECT AVG(TREATMENT_COST) FROM FACT_APPOINTMENT WHERE STATUS = 'Completed');

-- Q15. Patients who never had a Completed appointment
SELECT P.PATIENT_ID, P.PATIENT_NAME
FROM DIM_PATIENT P
WHERE P.PATIENT_ID NOT IN (SELECT DISTINCT PATIENT_ID FROM FACT_APPOINTMENT WHERE STATUS = 'Completed');

-- Q16. Top 5 patients by total billing amount
SELECT P.PATIENT_ID, P.PATIENT_NAME, SUM(F.BILLING_AMOUNT)
FROM FACT_APPOINTMENT F
JOIN DIM_PATIENT P ON F.PATIENT_ID = P.PATIENT_ID
GROUP BY P.PATIENT_ID, P.PATIENT_NAME
ORDER BY SUM(F.BILLING_AMOUNT) DESC
LIMIT 5;

-- Q18. Cost tier segmentation for completed appointments
SELECT APPOINTMENT_ID, TREATMENT_NAME, BILLING_AMOUNT,
    CASE
        WHEN BILLING_AMOUNT < 1000 THEN 'LOW'
        WHEN BILLING_AMOUNT BETWEEN 1000 AND 10000 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS COST_TIER
FROM FACT_APPOINTMENT
WHERE STATUS = 'Completed'
ORDER BY BILLING_AMOUNT DESC;

-- Q19. Patient age and age group
SELECT PATIENT_ID, PATIENT_NAME, DOB,
    DATEDIFF(YEAR, DOB, CURRENT_DATE()) AS AGE,
    CASE
        WHEN AGE < 18 THEN 'CHILD'
        WHEN AGE BETWEEN 18 AND 50 THEN 'ADULT'
        ELSE 'SENIOR'
    END AS AGE_GROUP
FROM DIM_PATIENT
ORDER BY AGE;

-- Q20. New patients registered each year
SELECT YEAR(REGISTRATION_DATE) AS REG, COUNT(*)
FROM DIM_PATIENT
GROUP BY REG
ORDER BY REG;

-- Q21. Appointment count by weekday (patient footfall pattern)
SELECT D.WEEKDAY, COUNT(*)
FROM FACT_APPOINTMENT F
JOIN DIM_DATE D ON D.DATE_ID = F.DATE_ID
GROUP BY D.WEEKDAY
ORDER BY COUNT(*) DESC;

-- Q22. Rank doctors within their department by appointment count
SELECT D.DOCTOR_NAME, DE.DEPARTMENT_NAME, COUNT(F.APPOINTMENT_ID),
    RANK() OVER (PARTITION BY DE.DEPARTMENT_NAME ORDER BY COUNT(F.APPOINTMENT_ID) DESC) AS RANKING
FROM FACT_APPOINTMENT F
JOIN DIM_DOCTOR D      ON D.DOCTOR_ID = F.DOCTOR_ID
JOIN DIM_DEPARTMENT DE ON DE.DEPARTMENT_ID = F.DEPARTMENT_ID
GROUP BY D.DOCTOR_NAME, DE.DEPARTMENT_NAME;

-- Q23. Running total of revenue per department over time
SELECT DE.DEPARTMENT_NAME, D.FULL_DATE, SUM(F.BILLING_AMOUNT) AS TOTAL,
    SUM(SUM(F.BILLING_AMOUNT)) OVER (
        PARTITION BY DE.DEPARTMENT_NAME ORDER BY D.FULL_DATE DESC
    ) AS RUNNING_TOTAL
FROM FACT_APPOINTMENT F
JOIN DIM_DEPARTMENT DE ON DE.DEPARTMENT_ID = F.DEPARTMENT_ID
JOIN DIM_DATE D         ON D.DATE_ID = F.DATE_ID
GROUP BY DE.DEPARTMENT_NAME, D.FULL_DATE
ORDER BY DE.DEPARTMENT_NAME, D.FULL_DATE;

-- Q24. Top-earning doctor in each department (CTE)
WITH TOPEARNING AS (
    SELECT DE.DEPARTMENT_NAME, D.DOCTOR_NAME, SUM(F.BILLING_AMOUNT) AS TOTAL_REVENUE,
        RANK() OVER (PARTITION BY DE.DEPARTMENT_NAME ORDER BY SUM(F.BILLING_AMOUNT) DESC) AS RANKING
    FROM FACT_APPOINTMENT F
    JOIN DIM_DEPARTMENT DE ON DE.DEPARTMENT_ID = F.DEPARTMENT_ID
    JOIN DIM_DOCTOR D      ON D.DOCTOR_ID = F.DOCTOR_ID
    GROUP BY DE.DEPARTMENT_NAME, D.DOCTOR_NAME
)
SELECT * FROM TOPEARNING WHERE RANKING = 1;

-- Q26. Patient visit leaderboard (dense rank by visit count)
SELECT P.PATIENT_ID, P.PATIENT_NAME, COUNT(*) AS HOWMANYTIME,
    DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS LOTVISIT
FROM FACT_APPOINTMENT F
JOIN DIM_PATIENT P ON P.PATIENT_ID = F.PATIENT_ID
GROUP BY P.PATIENT_ID, P.PATIENT_NAME;

/* ============================================================================
   END
   ============================================================================ */
